### ISSUE TITLE
S'assurer de la faisabilité de transférer un model yoloV4 en .tflite

### ISSUE THREAD

**Issue by robinmailhot** [ethanlefebv/S4H2021-Scarus#3]

**Comment by ethanlefebv** [comment]
@robinmailhot, je te recommande d'ajouter un commentaire lorsque tu mets une tâche comme Done ou Closed, ainsi que d'ajouter un label pour indiquer si c'est complété, wontfix, etc.

**Comment by robinmailhot** [comment]
Il est faisable de transérer les weights en un model .tflite.
code here : https://github.com/theAIGuysCode/tensorflow-yolov4-tflite
