### ISSUE TITLE
Rod's support 

### ISSUE THREAD

**Issue by AnthonyTurgeon-B** [ethanlefebv/S4H2021-Scarus#41]
CAD of motors' support between the rod and the bearings that support the load.

**Comment by Tilec99** [comment]
i think its the same as "CAD motor's support", 2 times the same task???

**Comment by AnthonyTurgeon-B** [comment]
As-tu compris la difference, je m'etais mal exprimer mdr?

**Comment by Tilec99** [comment]
yes, the name of the part is important

**Comment by Tilec99** [comment]
![image.png](https://images.zenhubusercontent.com/60084e88a918c9835689f135/180368e6-b278-49e2-a956-1ac700beccf5)
