### ISSUE TITLE
CAD Joint protection

### ISSUE THREAD

**Issue by AnthonyTurgeon-B** [ethanlefebv/S4H2021-Scarus#42]
CAD of a joint's protection, in particular to protect the bearings inside the assembly. 
There are two of these: one on the top of the joint, the other at the bottom.

**Comment by Tilec99** [comment]
![image.png](https://images.zenhubusercontent.com/60084e88a918c9835689f135/37f3af4d-2961-4680-9aa7-96a176dcbfe6)
