### ISSUE TITLE
CAD of motors' support (box)

### ISSUE THREAD

**Issue by AnthonyTurgeon-B** [ethanlefebv/S4H2021-Scarus#43]
CAD of a support, a wooden box, that can be assemble with the slide and that will support the robot by the motors. Holes are cut to indicate where to put the motors.  It will also have premade holes on a false bottom to fix the OpenCR and Raspberry Pi and holes for the wires and plugs.

**Comment by Tilec99** [comment]
![image.png](https://images.zenhubusercontent.com/60084e88a918c9835689f135/7b6bf7a1-c0e9-4c61-bc98-3d249f1a73b9)
