### ISSUE TITLE
CAD of the rod's support bearing covers

### ISSUE THREAD

**Issue by AnthonyTurgeon-B** [ethanlefebv/S4H2021-Scarus#50]
CAD the pieces that protect the bearings that are supporting the rod that support the robot's frame. 
There are two of these: one on the top of the support, the other at the bottom.

**Comment by Tilec99** [comment]
![image.png](https://images.zenhubusercontent.com/60084e88a918c9835689f135/17b75bad-639d-4c05-8c96-8f21233c1595)
